# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: build

  run:
    cmds:
      - task: build
      - ./dist/get-latest

  build:
    cmds:
      - go mod tidy
      - CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-w -extldflags "-static"' -o ./dist/get-latest
